services:
  backend:
    build:
      context: ./app/backend
    container_name: fp-backend
    environment:
      - MODEL_BASE_URL=${MODEL_BASE_URL:-}
    ports:
      - "7860:7860"
    restart: unless-stopped

  frontend:
    build:
      context: ./app/frontend
    container_name: fp-frontend
    depends_on:
      - backend
    ports:
      - "8080:80"
    restart: unless-stopped
    volumes:
      - ./app/frontend/nginx.local.conf:/etc/nginx/conf.d/default.conf
