---
- hosts: k8s
  become: yes
  tasks:
    - name: Installer le moteur Docker disponible (moby-engine ou docker)
      shell: dnf install -y docker moby-engine || yum install -y docker

    - name: Demarrer et activer Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Configurer Docker pour systemd
      shell: |
        mkdir -p /etc/docker
        echo '{"exec-opts": ["native.cgroupdriver=systemd"]}' > /etc/docker/daemon.json

    - name: Redemarrer Docker
      service:
        name: docker
        state: restarted