[all:vars]
ansible_user=ec2-user
ansible_ssh_private_key_file=/home/hadoop/key.pem
ansible_ssh_extra_args='-o StrictHostKeyChecking=no'
ansible_python_interpreter=/usr/bin/python3

[master]
master-node ansible_host=34.254.185.90

[worker]
worker-node ansible_host=54.228.151.1

[k8s:children]
master
worker